name: publish-testpypi

on:
  push:
    tags:
      - '*.*.*-test.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check-out repo and set-up python
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # install & configure poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # configure credentials
      - name: Configure credentials
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}

      # build package
      - name: Build package
        run: poetry build

      # publish package
      - name: Publish package
        run: poetry publish --repository testpypi
